export const actions = {
  HANDLE_DIFFICULTY_BUTTON: 'HANDLE_DIFFICULTY_BUTTON',
  GENERATE_CELLS: 'GENERATE_CELLS',
  PLACE_MINES: 'PLACE_MINES',
  PLACE_NUMBERS: 'PLACE_NUMBERS',
  HANDLE_CLICK: 'HANDLE_CLICK',
};
